const pakistanCities = [
    'Online',
    'Abbottabad',
    'Adezai',
    'Ahmadpur East',
    'Aijazabad',
    'Akora Khattak',
    'Alipur',
    'Arifwala',
    'Attock',
    'Bahawalnagar',
    'Bahawalpur',
    'Bannu',
    'Bhalwal',
    'Bhakkar',
    'Bhimber',
    'Buner',
    'Chakdara',
    'Chakwal',
    'Chiniot',
    'Dadu',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Dera Murad Jamali',
    "Faisalabad",
    'Gawadar',
    'Gilgit',
    'Gujranwala',
    'Gujrat',
    'Gujar Khan',
    'Hala',
    'Hangu',
    'Haripur',
    'Hyderabad',
    'Islamabad',
    'Jacobabad',
    'Jaffarabad',
    'Jhang',
    'Jhelum',
    'Karachi',
    'Karak',
    'Karakoram',
    'Khanewal',
    'Khanpur',
    'Khairpur',
    'Khushab',
    'Kotli',
    'Lakki Marwat',
    'Lahore',
    'Lasbela',
    'Larkana',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Malakand',
    'Multan',
    'Murree',
    'Nawabshah',
    'Narowal',
    'Nowshera',
    'Okara',
    'Panjgur',
    'Parachinar',
    'Pakpattan',
    'Peshawar',
    'Quetta',
    'Rajanpur',
    'Rawalpindi',
    'Saddar',
    'Sahiwal',
    'Sargodha',
    'Shikarpur',
    'Sheikhupura',
    'Skardu',
    'Sibi',
    'Sialkot',
    'Sukkur',
    'Swabi',
    'Swat',
    'Tando Adam',
    'Tando Allahyar',
    'Tando Muhammad Khan',
    'Tank',
    'Turbat',
    'Umerkot',
    'Vihari',
    'Wazirabad',
    'Zhob',
    'Ziarat',
    'Abbotabad',
    'Aftababad',
    'Ahsanabad',
    'Alahabad',
    'Alipur',
    'Amirabad',
    'Ameenabad',
    'Arah',
    'Arifwala',
    'Atdai',
    'Ayubia',
    'Badin',
    'Bahawalpur',
    'Bannu',
    'Bhalwal',
    'Bhakkar',
    'Bhimber',
    'Buner',
    'Chakwal',
    'Chiniot',
    'Dadu',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Dera Murad Jamali',
    'Gawadar',
    'Gilgit',
    'Gujranwala',
    'Gujrat',
    'Gujar Khan',
    'Hala',
    'Hangu',
    'Hyderabad',
    'Islamabad',
    'Jacobabad',
    'Jhang',
    'Jhelum',
    'Karachi',
    'Karak',
    'Khanewal',
    'Khanpur',
    'Khairpur',
    'Khushab',
    'Kotli',
    'Lakki Marwat',
    'Lahore',
    'Lasbela',
    'Larkana',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Malakand',
    'Multan',
    'Nawabshah',
    'Narowal',
    'Nowshera',
    'Okara',
    'Panjgur',
    'Parachinar',
    'Pakpattan',
    'Peshawar',
    'Quetta',
    'Rajanpur',
    'Rawalpindi',
    'Saddar',
    'Sahiwal',
    'Sargodha',
    'Shikarpur',
    'Sheikhupura',
    'Skardu',
    'Sibi',
    'Sialkot',
    'Sukkur',
    'Swabi',
    'Swat',
    'Tando Adam',
    'Tando Allahyar',
    'Tank',
    'Turbat',
    'Wazirabad',
    'Zhob',
    'Ziarat',
    'Abbottabad',
    'Awaran',
    'Badin',
    'Bannu',
    'Bhalwal',
    'Bhakkar',
    'Bhimber',
    'Buner',
    'Chakwal',
    'Chiniot',
    'Dadu',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Dera Murad Jamali',
    'Gawadar',
    'Gilgit',
    'Gujranwala',
    'Gujrat',
    'Gujar Khan',
    'Hala',
    'Hangu',
    'Hyderabad',
    'Islamabad',
    'Jacobabad',
    'Jhang',
    'Jhelum',
    'Karachi',
    'Karak',
    'Khanewal',
    'Khanpur',
    'Khairpur',
    'Khushab',
    'Kotli',
    'Lakki Marwat',
    'Lahore',
    'Lasbela',
    'Larkana',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Malakand',
    'Multan',
    'Nawabshah',
    'Narowal',
    'Nowshera',
    'Okara',
    'Panjgur',
    'Parachinar',
    'Pakpattan',
    'Peshawar',
    'Quetta',
    'Rajanpur',
    'Rawalpindi',
    'Saddar',
    'Sahiwal',
    'Sargodha',
    'Shikarpur',
    'Sheikhupura',
    'Skardu',
    'Sibi',
    'Sialkot',
    'Sukkur',
    'Swabi',
    'Swat',
    'Tando Adam',
    'Tando Allahyar',
    'Tank',
    'Turbat',
    'Umerkot',
    'Wazirabad',
    'Zhob',
    'Ziarat'
];


export default pakistanCities